export const LOCALSTORAGE = {
  CURRENT_SECTION_LIST: "CURRENT_SECTION_LIST",
  CURRENT_SECTION_LOCATION: "CURRENT_SECTION_LOCATION",
  CURRENT_SECTION_INSTRUCTIONS: "CURRENT_SECTION_INSTRUCTIONS",
  RUNTIME_INFO: "RUNTIME_INFO",
  RUNTIME_CHECK_ACTIONS: "RUNTIME_CHECK_ACTIONS",
  RUNTIME_INSTRUCTIONS_INPUTS: "RUNTIME_INSTRUCTIONS_INPUTS",
  CURRENT_RUNTIME_STATUS: "CURRENT_RUNTIME_STATUS",
};
